---

dist: bionic
matrix:
  fast_finish: true
  include:
    - os: linux
      env: ANSIBLE_VER="2.8"; TEST_SCENARIO="default"
      services: docker
      language: python
      python: "3.7"

install:
  - pip install ansible==$ANSIBLE_VER.* testinfra molecule docker
script:
  - molecule --version
  - ansible --version
  - molecule test -s $TEST_SCENARIO
