#!/bin/bash

export MOLIMG="fedora/33"
export MOLECULE_SCENARIO="default"
export ANSIBLE_VAULT_PASSWORD_FILE="$XDG_CONFIG_HOME/ansible/ci-secret"
# https://github.com/ansible/ansible/issues/67004
export ANSIBLE_PIPELINING=false
