---
dependency:
  name: galaxy
driver:
  name: lxd
lint: |
    set -e
    PATH=${PATH}
    yamllint .
    ansible-lint .
    ansible-lint molecule/resources/playbooks/converge.yml
    flake8
platforms:
  - name: "pyenv-${MLDISTRO:-focal}"
    alias: "${MLIMG:-ubuntu/focal}"
provisioner:
  name: ansible
  options:
    vvv: true
  playbooks:
    create: ../resources/playbooks/create.yml
    converge: ../resources/playbooks/converge.yml
    destroy: ../resources/playbooks/destroy.yml
  env:
    TEST_CASE: default
verifier:
  name: testinfra
  directory: ../resources/tests/
  env:
    TEST_CASE: default
  options:
    verbose: true
