---
- name: Converge
  hosts: all
  vars:
    latest_python: 3.7.4
    pyenv_virtualenvs:
      - venv_name: "neovim"
        py_version: "{{ latest_python }}"
    pyenv_python_versions:
      - "{{ latest_python }}"
  tasks:
    - name: Adjust id on manjaro
      lineinfile:
        dest: /etc/os-release
        regexp: 'ID=.*'
        line: 'ID=arch'
        state: present
      when: ansible_os_family == "Archlinux"

    - name: run ansible-pyenv role
      include_role:
        name: ansible-pyenv
