---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
    yamllint .
    ansible-lint .
    ansible-lint molecule/resources/playbooks/converge.yml
    flake8
platforms:
  - name: "ansible-pyenv-${MOLECULE_DISTRIBUTION:-ubuntu18}"
    image: "${MOLECULE_IMAGE:-quay.io/samdoran/ubuntu18-ansible}"
    command: ${MOLECULE_COMMAND:-""}
    dockerfile: ../resources/playbooks/Dockerfile.j2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: false
provisioner:
  name: ansible
  env:
    TEST_CASE: default
  options:
    vvv: true
  playbooks:
    converge: ../resources/playbooks/converge.yml
verifier:
  name: testinfra
  directory: ../resources/tests/
  env:
    TEST_CASE: user
  options:
    verbose: true
