# molecule/dnf/Dockerfile.j2

FROM {{ item.image }}

RUN rm -f /lib/systemd/system/systemd*udev* \
 && rm -f /lib/systemd/system/getty.target \
 && if [ $(command -v dnf) ]; then \
        echo "fastestmirror=true" >> /etc/dnf/dnf.conf; \
        echo "minrate=10k" >> /etc/dnf/dnf.conf; \
        echo "timeout=10" >> /etc/dnf/dnf.conf; \
    fi

