---
- name: Converge
  hosts: all
  tasks:
    - name: Adjust id on manjaro
      lineinfile:
        dest: /etc/os-release
        regexp: 'ID=.*'
        line: 'ID=arch'
        state: present
      when: ansible_os_family == "Archlinux"

    - name: Add test user
      user:
        name: test
        shell: /bin/zsh

    - name: run ansible-pyenv role
      include_role:
        name: ansible-pyenv
      vars:
        pyenv_user: test
