name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: bonddim/action-lxd@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - uses: actions/checkout@v2
        with:
          path: format(${{ github.repository }}, "ansible-", "")

      - run: |
          pip3 install ansible >= 2.8 testinfra molecule molecule-lxd docker flake8 ansible-lint yamllint
          
      - run: |
          python --version
          molecule --version
          ansible --version
      
      - run: |
          molecule test -s default


